### ISSUE TITLE
Another Indonesian Translation Project

### ISSUE THREAD

**Issue by didikz** [adityapurwa/id.vuejs.org#20]
Hi @adityapurwa I recently saw that there is another Indonesian translation project in this repository https://github.com/vuejs-id/docs. Any thoughts?

**Comment by adityapurwa** [comment]
Hi @didikz  thank you for bringing this up to me. I knew about the repository weeks before I decided to start this repository. I noticed that it was inactive at that time, so I thought it was old and not updated to the latest version of the official repository. That's why I decided to start a new translation to avoid having too many syncs with the official Vue.js docs repository.

I actually reached and posted to Vue.js Indonesia about the translation project that I am starting, but they wanted for me to maintain their existing project instead; which I refused, because I already started working on some translation and doing the logistics for moving my translation and syncing up with their repository would just add more work for me.

Anyway, I noticed that their repository is now active again. So, I think we now have 2 active translation in progress.

I personally, would continue this repository as we've already done so much work and it would be a waste to drop it. For everyone else, it would be their own decision to chose on which repository to contribute.

Once again, thank you for bringing this up to me. Feel free to shoot me an e-mail to discuss more.
